{% set name = "carto-auth" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 982d293d723e92dc334734a7be43a113dd7c8ce8c5d97b49d86c2ad81d1c63a5
  # pypi tarball doesn't include tests
  - git_url: https://github.com/CartoDB/carto-auth.git
    git_rev: v{{ version }}
    folder: gh_src

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - requests
    - pyyaml

test:
  imports:
    - carto_auth
  requires:
    - pip
    - pytest
    - pytest-mock
    - requests-mock
  source_files:
    - gh_src/tests
  commands:
    - pip check
    - cd gh_src
    # "test_carto_dw_client" requires google.cloud.bigquery
    # which is an extra requirement
    - pytest tests -k "not test_carto_dw_client"

about:
  home: https://github.com/cartodb/carto-auth
  summary: Python library to authenticate with CARTO
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/CartoDB/carto-auth/tree/master/docs
  dev_url: https://github.com/cartodb/carto-auth
  description: Python library to authenticate with CARTO

extra:
  recipe-maintainers:
    - Jesus89
